easy_admin:
    site_name: 'Senauto Rent'
    design:
        brand_color: '#1ABC9C'
        menu:
          - label: 'Bookings'
            icon: 'calendar-check'
            children:
              - {entity: 'Customer', label: 'Customers', icon: 'user-tie'}
              - {entity: 'Reservation', label: 'Bookings', icon: 'tasks'}
          - label: 'Fleet'
            icon: 'parking'
            children:
              - { entity: 'Car', label: 'Cars', icon: 'car' }
              - {entity: 'Driver', label: 'Drivers', icon: 'id-badge'}
              - { entity: 'CarModel', label: 'Car Models', icon: 'car' }
              - { entity: 'CarType', label: 'Car Categories', icon: 'shuttle-van' }
              - { entity: 'CarBrand', label: 'Manufacturers', icon: 'industry' }
          - label: 'Settings'
            icon: 'cog'
            children:
              - {entity: 'User', label: 'Users', icon: 'user'}
              - {entity: 'ReservationOption', label: 'Reservation Options', icon: 'sliders-h'}
    user:
        display_name: true
        name_property_path: 'name'
        display_avatar: true
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    list:
        actions: ['show','edit','delete','search']
    entities:
      Car:
        class: App\Entity\Car
        list:
          title: Cars
          actions: [ {name: new, label: 'Add Car', icon: plus}, show, edit, delete ]
          fields: ['id', 'model', 'immatriculation', 'status', {property: 'modified', label: 'Last update'}, {property: 'modifiedby.name', label: 'Updated by'}]
        show:
          fields:
            - { property: 'model.image', type: 'image', base_path: '%app.path.car_model_images%' }
            - model
            - color
            - chassisNumber
            - immatriculation
            - catalogValue
            - residualValue
            - location
            - rentPerDay
            - fuelQuantity
            - lastOdometer
            - numberOfSeats
            - numberOfDoors
            - transmission
            - fuelCase
            - co2Emission
            - horsePower
            - power
        edit:
          fields: 
            - { type: 'group', columns: 4, label: 'Basic information' }
            - model
            - { property: 'color', type: 'color' }
            - chassisNumber
            - immatriculation
            - catalogValue
            - residualValue
            - { type: 'group', columns: 4, label: 'Assets' }
            - numberOfSeats
            - numberOfDoors
            - { property: 'transmission', type: 'choice', type_options: { choices: {'Automatic': 'Automatic', 'Manual': 'Manual'} } }
            - { property: 'fuelCase', type: 'choice', type_options: { choices: {'Gasoline': 'gasoline', 'Diesel': 'diesel'} } }
            - co2Emission
            - horsePower
            - power
            - { type: 'group', columns: 4, label: 'Services' }
            - location
            - { property: 'rentPerDay', type: 'money', type_options: { currency: 'XOF' } }
            - { property: 'fuelQuantity', label: 'Tank Level' }
            - lastOdometer
        new:
          fields: 
            - { type: 'tab', columns: 4, label: 'Basic information' }
            - { property: 'model', label: 'Car Model' }
            - { property: 'color', type: 'color' }
            - chassisNumber
            - immatriculation
            - catalogValue
            - residualValue
            - { type: 'tab', columns: 4, label: 'Assets' }
            - numberOfSeats
            - numberOfDoors
            - { property: 'transmission', type: 'choice', type_options: { choices: {'Automatic': 'Automatic', 'Manual': 'Manual'} } }
            - { property: 'fuelCase', type: 'choice', type_options: { choices: {'Gasoline': 'gasoline', 'Diesel': 'diesel'} } }
            - co2Emission
            - horsePower
            - power
            - { type: 'tab', columns: 4, label: 'Services' }
            - location
            - rentPerDay
            - { property: 'fuelQuantity', type: 'integer', label: 'Tank Level' }
            - lastOdometer
            
      CarModel:
        class: App\Entity\CarModel
        controller: App\Controller\AdminController
        list:
          actions: [ {name: new, label: 'Add Model', icon: plus}, show, edit, delete ]
          title: Car Models
          fields: [id, label, {property: brand.label, label: Manufacturer}, modified, {property: modifiedby.name, label: Modified by}]
        show:
          fields:
            - { property: 'image', type: 'image', base_path: '%app.path.car_model_images%' }
            - label
            - {property: brand.label, label: Manufacturer}
            - year
            - created
            - {property: createdby.name, label: Created by}
            - modified
            - {property: modifiedby.name, label: Modified by}
            - versionHistory
        form:
          title: Edit Car Model
          fields:
            - { type: 'group', columns: 4, label: 'Model Image' }
            - { property: 'imageFile', type: 'vich_image' }
            - { type: 'group', columns: 8, label: 'Model Properties' }
            - brand
            - label
            - year

      CarType:
        class: App\Entity\CarType

      CarBrand:
        class: App\Entity\CarBrand
      
      Reservation:
        class: App\Entity\Reservation
        controller: App\Controller\ReservationController
        form:
          fields:
            - { type: 'tab', label: 'Car reservation' }
            - pickupLocation
            - { property: 'pickupDate', type_options: { widget: 'single_text' }  }
            - dropoffLocation
            - { property: 'dropoffDate', type_options: { widget: 'single_text' }  }
            - reservedCar
            - { type: 'tab', label: 'Booking Options' }
            - { property: 'options', type: entity, type_options: { class: App\Entity\ReservationOption, choice_label: priceLabel, multiple: true, expanded: true} } 
            - dailyRate
            - {property: discountType, type: choice, type_options: { choices: {'Fixed amount': 'Fixed', 'Percent': 'Percent'}}}
            - discount
            - { type: 'tab', label: 'Customer' }
            - customer

      ReservationOption:
        class: App\Entity\ReservationOption
        list:
          fields: [label, description, price]
        form:
          fields: [label, description, price]

      Customer:
        class: App\Entity\Customer
        actions: [show, edit, delete, new, search]
        list:
          fields: [id, name, customerType, email, phone]
        show:
          fields: [{ property: 'image', type: 'image', base_path: '%app.path.customers_images%' }, name, customerType, email, {property: phone, label: Phone Number}, birthDate, { property: 'idCardProof', type: 'image', base_path: '%app.path.idcards_images%' }, idCardType, idCardNumber, userAccount, created, {property: createdby.name, label: Created by}, modified, {property: modifiedby.name, label: Modified by}, versionHistory]
        form:
          fields: 
            - { type: 'group', columns: 4, label: 'Identity documents' }
            - { property: 'imageFile', type: 'vich_image' }
            - { property: 'idCardType', label: Type of ID Card, type: 'choice', type_options: { choices: {'Select the type of ID Card': '', 'Identity Card': 'Identity Card', 'Driver License': 'Driver License', 'Passport': 'Passport'} } }
            - { property: 'idcImageFile', type: 'vich_image' }
            - { property: 'idCardNumber', label: Number of ID Card }
            - { type: 'group', columns: 8, label: 'Identity' }
            - name
            - { property: 'customerType', type: 'choice', type_options: { choices: {'Person': 'Person', 'Enterprise': 'Enterprise'} } }
            - email
            - { property: 'phone', type: 'tel', label: Phone Number }
            - { property: 'birthDate', type_options: { widget: 'single_text' }  }

      Driver:
        class: App\Entity\Driver
        actions: [show, edit, delete, new, search]
        list:
          fields: [id, firstName, middleName, lastName, phone]
        show:
          fields: [{ property: 'image', type: 'image', base_path: '%app.path.idcards_images%' }, idCardNumber, firstName, middleName, lastName, {property: phone, label: Phone Number}, created, {property: createdby.name, label: Created by}, modified, {property: modifiedby.name, label: Modified by}, versionHistory]
        form:
          fields: 
            - { type: 'group', columns: 4, label: 'Identity documents' }
            - { property: 'imageFile', type: 'vich_image' }
            - { property: 'idCardNumber', label: Number of ID Card }
            - { type: 'group', columns: 8, label: 'Driver Information' }
            - firstName
            - middleName
            - lastName
            - { property: 'phone', type: 'tel', label: Phone Number }

      User:
        class: App\Entity\User
        controller: App\Controller\UserController
        list:
          fields: ['id','name', 'email', 'phoneNumber', 'roles']
        show:
          fields:
            - { property: 'name' }
            - { property: 'phoneNumber' }
            - { property: 'email' }
            - { property: 'roles'}
          actions:
            - { name: 'changePassword', css_class: 'btn btn-warning', icon: edit }
        new:
          fields: 
            - { type: 'group', columns: 6, label: 'Personal informations' }
            - { property: 'name', type: 'text' }
            - { property: 'phoneNumber', type: 'tel' }
            - { type: 'group', columns: 6, label: 'User credentials' }
            - { property: 'email', type: 'email' }
            - { property: 'password', type: 'password' }
            - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, choices: {'Employee': 'ROLE_USER', 'Manager': 'ROLE_ADMIN', 'SUPER ADMIN': 'ROLE_SUPER_ADMIN'} } }
        edit:
          fields: 
            - { type: 'group', columns: 6, label: 'Personal informations' }
            - { property: 'name', type: 'text' }
            - { property: 'phoneNumber', type: 'tel' }
            - { type: 'group', columns: 6, label: 'User credentials' }
            - { property: 'email', type: 'email' }
            - { property: 'password', type: 'password' }
            - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, choices: {'Employee': 'ROLE_USER', 'Manager': 'ROLE_ADMIN', 'SUPER ADMIN': 'ROLE_SUPER_ADMIN'} } }
