vich_uploader:
    db_driver: orm

    mappings:
        car_model_images:
            uri_prefix: '%app.path.car_model_images%'
            upload_destination: '%kernel.project_dir%/public/images/carmodels'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true

        customers_images:
            uri_prefix: '%app.path.customers_images%'
            upload_destination: '%kernel.project_dir%/public/images/customers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
        
        idcards_images:
            uri_prefix: '%app.path.idcards_images%'
            upload_destination: '%kernel.project_dir%/public/images/idcards'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
        
        manufacturers_images:
            uri_prefix: '%app.path.manufacturers_images%'
            upload_destination: '%kernel.project_dir%/public/images/manufacturers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
