easy_admin:
  entities:
    Driver:
        class: App\Entity\Driver
        actions: [show, edit, delete, new, search]
        list:
          fields: [id, firstName, middleName, lastName, phone]
        show:
          fields: [{ property: 'image', type: 'image', base_path: '%app.path.idcards_images%' }, idCardNumber, firstName, middleName, lastName, {property: phone, label: Phone Number}, created, {property: createdby.name, label: Created by}, modified, {property: modifiedby.name, label: Modified by}, versionHistory]
        form:
          fields: 
            - { type: 'group', columns: 4, label: 'Identity documents' }
            - { property: 'imageFile', type: 'vich_image' }
            - { property: 'idCardNumber', label: Number of ID Card }
            - { type: 'group', columns: 8, label: 'Driver Information' }
            - firstName
            - middleName
            - lastName
            - { property: 'phone', type: 'tel', label: Phone Number }