easy_admin:
  entities:
    Reservation:
        class: App\Entity\Reservation
        controller: App\Controller\ReservationController
        disabled_actions: ['delete']
        list:
          fields: [customer, reservedCar, pickupDate, dropoffDate, dailyRate, status]
        show:
          actions:
            - {name: approve, label: Approve Reservation, icon: calendar-check, css_class: btn btn-success}
            - {name: confirm, label: Confirm Reservation, icon: calendar-check, css_class: btn btn-info}
            - {name: acceptquote, label: Accept Quotation, icon: calendar-check, css_class: btn btn-warning}
          fields: 
            - customer
            - customer.phone
            - customer.email
            - reservedCar
            - { property: 'reservedCar.model.image', type: 'image', base_path: '%app.path.car_model_images%', css_class: 'img-fluid', type_options: {attr: {class: 'img-fluid'}} }
            - reservedCar.model
            - pickupDate
            - pickupLocation
            - dropoffDate
            - dropoffLocation
            - numberOfDays
            - dailyRate
            - discount
            - driver
            - options
            - {property: status}
            - created
            - createdby.name
            - modified
            - modifiedby.name
            - versionHistory
        form:
          fields:
            - { type: 'tab', label: 'Car reservation' }
            - {property: pickupLocation, type: choice, type_options: { choices: {'': '', 'Airport': 'Airport to agency', 'Agency': 'Agency', 'Office': 'Office', 'Home': 'Home' }}}
            - { property: 'pickupDate', type: date, type_options: { widget: 'single_text' }  }
            - {property: dropoffLocation, type: choice, type_options: { choices: {'': '', 'Airport': 'Airport to agency', 'Agency': 'Agency', 'Office': 'Office', 'Home': 'Home' }}}
            - { property: 'dropoffDate', type: date, type_options: { widget: 'single_text' }  }
            - reservedCar
            - { type: 'tab', label: 'Booking Options' }
            - { property: 'options', type: entity, type_options: { class: App\Entity\ReservationOption, choice_label: priceLabel, multiple: true, expanded: true} } 
            - driver
            - { property: dailyRate }
            - {property: discountType, type: choice, type_options: { choices: {'Fixed amount': 'Fixed', 'Percent': 'Percent'}}}
            - { property: discount}
            - { type: 'tab', label: 'Customer' }
            - customer
            - {property: rentingPurpose, type: choice, type_options: { choices: {'': '', 'Business': 'Business', 'Leisure': 'Leisure', 'Cortege': 'Cortege', 'VTC': 'VTC', 'Wedding': 'Wedding' }}}
        templates:
          show: 'easyadmin/reservation/show_reservation.html.twig'

    ReservationOption:
      class: App\Entity\ReservationOption
      list:
        fields: [label, description, price]
      form:
        fields: [label, description, price]

    Customer:
        class: App\Entity\Customer
        actions: [show, edit, delete, new, search]
        list:
          fields: [id, name, customerType, email, phone]
        show:
          fields: [{ property: 'image', type: 'image', base_path: '%app.path.customers_images%' }, name, customerType, email, {property: phone, label: Phone Number}, birthDate, { property: 'idCardProof', type: 'image', base_path: '%app.path.idcards_images%' }, idCardType, idCardNumber, userAccount, created, {property: createdby.name, label: Created by}, modified, {property: modifiedby.name, label: Modified by}, versionHistory]
        form:
          fields: 
            - { type: 'group', columns: 4, label: 'Identity documents' }
            - { property: 'imageFile', type: 'vich_image' }
            - { property: 'idCardType', label: Type of ID Card, type: 'choice', type_options: { choices: {'Select the type of ID Card': '', 'Identity Card': 'Identity Card', 'Driver License': 'Driver License', 'Passport': 'Passport'} } }
            - { property: 'idcImageFile', type: 'vich_image' }
            - { property: 'idCardNumber', label: Number of ID Card }
            - { type: 'group', columns: 8, label: 'Identity' }
            - name
            - { property: 'customerType', type: 'choice', type_options: { choices: {'Person': 'Person', 'Enterprise': 'Enterprise'} } }
            - email
            - { property: 'phone', type: 'tel', label: Phone Number }
            - { property: 'birthDate', type_options: { widget: 'single_text' }  }

    Contract:
      class: App\Entity\ReservationContract
      list:
        actions: ['-new', '-edit', '-delete']
      show:
        actions: ['-new', '-edit', '-delete']